### ISSUE TITLE
Pages not rendering/URL problem

### ISSUE THREAD

**Issue by nabobalis** [jumasy/AST5110#6]
The sidebar URL I think will need updating due to the ownership change.

In the meantime, that old URL does not render for me nor what I think should be the new url: https://jumasy.github.io/AST5110/

It is very possible that I broke it when I updated the CI.

There might be a GitHub setting to tweak?

**Comment by AvijeetPrasad** [comment]
I think we need to update the GitHub pages tabs under the repository settings. 

On Settings -> Pages, we need to choose settings for Build and deployment. Most likely this can be done by choosing gh-pages under the branch option. 

For details see
https://jupyterbook.org/en/stable/publish/gh-pages.html

**Comment by AvijeetPrasad** [comment]
Now, the link: https://jumasy.github.io/AST5110/AST5110.wiki/Home.html works as expected. It has been added to the repo overview.
